[workspace]
authors = ["Dhimitrios Duka <dhimitrios.duka1@gmail.com>"]
channels = ["nvidia", "conda-forge", "pytorch", "default"]
name = "AVION"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
compile-decord = """
bash -c '
    cd third_party/decord/
    rm -rf build
    mkdir build && cd build
    cmake .. -DUSE_CUDA=0 -DCMAKE_BUILD_TYPE=Release
    make
    cd ../python
    python3 setup.py install --user
    PYTHONPATH=$PYTHONPATH:$PWD
    python -c "import decord; print(decord.__path__)"
'
"""

[dependencies]
python = "==3.10"
pip = ">=25.2,<26"
einops = "==0.6.0"
ffmpeg = "4.*"
make = "*"
cmake = "*"
packaging = ">=25.0,<26"
wandb = ">=0.21.1,<0.22"

[pypi-dependencies]
torch = "==1.13.1+cu117"
torchvision = "==0.14.1+cu117"
torchaudio = "==0.13.1+cu117"
kornia = "==0.6.10"
pandas = "==1.5.3"
pytorchvideo = "==0.1.5"
scikit-learn = "==1.2.2"
submitit = "==1.4.5"
timm = "==0.6.12"
transformers = "==4.26.1"
flash-attn = "==0.2.8"
clip = { git = "https://github.com/openai/CLIP.git" }
black = ">=25.1.0, <26"

[pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu117"]
no-build-isolation = ["flash-attn"]
